### ISSUE TITLE
alfred workflow support

### ISSUE THREAD

**Issue by u2003** [marginnoteapp/raycast#1]
I notice that there is no release of raycast addon yet. I'm a crazy user of Alfred, and I like alfred more than raycast because of its ability to specify where to search/what to do using prefixes, as I customized the whole series of prefixes which are highly efficient while really easy to remember. I highly rely on the Zothero, Obsidian, OmniFocus and many other robust workflows, which are quite helpful to index all my important documents, notes and materials, to search on given websites, etc. I also made a workflow to pass selection/clipboard contents into Alfred which helps a lot to boost up this process. But till now there is still no one for MarginNote working like the above to index all the notes in it. I do hope you can please take it into consideration, I believe that'll build up to a large extent the flexibility of MarginNote on Mac!

**Comment by ourongxing** [comment]
Just wait for a moment. Everything is possible.
